[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
bevy_ecs = { version = "0.17", optional = true }
bitcode = { workspace = true }
serde = { version = "1.0", features = ["derive"] }

[features]
default = []
bevy = ["dep:bevy_ecs"]
