name: DB seeder push

on:
  push:
    paths:
      - ".github/workflows/db-seeder-push.yml"
      - "db/seeder/**"
  workflow_dispatch:

permissions:
      id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: rejdeboer
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: "db/seeder/Dockerfile"
          push: true
          tags: rejdeboer/mmo-db-seeder:latest

  modify-manifest:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Check out config repo
        uses: actions/checkout@v3
        with:
          repository: 'rejdeboer/mmo-deployment'

      - name: Modify application image
        run: |
          git config user.email rick.deboer@live.nl
          git config user.name rejdeboer
          sed -i "s+rejdeboer/mmo-db-seeder:.*+rejdeboer/mmo-db-seeder:${{ github.sha }}+g" deploy/base/db-seeder.yml
          git add .
          git commit -m 'automated: update mmo-db-seeder image'
          git push origin master
